version: '3.9'
services:
  aut_landing_web_test: 
    container_name: aut_landing_web_test
    image: aut_landing_web_test
    build: ./

  aut_landing_nginx_test:
    container_name: aut_landing_nginx_test
    image: aut_landing_nginx_test
    build: ./nginx
    ports:
      - 3003:9090

networks:
  aut_landing_test: