upstream nextjs {
    server autos_landing:3000;
}

server {
    listen 9080;
    server_name _;
    server_tokens off;

    # ----- Common proxy settings -----
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_bypass $http_upgrade;

    # ----- Built Next.js Assets (cache forever) -----
    # Since file names include a unique identifier (cache busting)
    location ^~ /_next/static/ {
        proxy_cache STATIC;
        proxy_cache_valid 200 7d;
        proxy_pass http://nextjs;
        add_header X-Proxy-Cache $upstream_cache_status;
    }

    # ----- Other Static Assets (e.g. images) -----
    location ^~ /static/ {
        proxy_cache STATIC;
        proxy_ignore_headers Cache-Control;
        proxy_cache_valid 60m;
        proxy_pass http://nextjs;
        add_header X-Proxy-Cache $upstream_cache_status;
    }

    # ----- Dynamic Requests -----
    # Disable gzip here to avoid issues with WebSocket upgrades
    location / {
        gzip off;
        proxy_pass http://nextjs;
    }
}